<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["data_forms_lang", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit data_forms_lang
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "data_forms_lang/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldTitle" class="col-sm-2 control-label">Title</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Title", "size" => 30, "class" => "form-control", "id" => "fieldTitle"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFormId" class="col-sm-2 control-label">Form Of ID</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Form_ID", "type" => "number", "class" => "form-control", "id" => "fieldFormId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLangId" class="col-sm-2 control-label">Lang Of ID</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Lang_ID", "type" => "number", "class" => "form-control", "id" => "fieldLangId"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
