<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["cp_forms_replies", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create cp_forms_replies
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "cp_forms_replies/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldFormsResponse" class="col-sm-2 control-label">Forms Of Response</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Forms_Response", "type" => "number", "class" => "form-control", "id" => "fieldFormsResponse"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDate" class="col-sm-2 control-label">Date</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Date", "size" => 30, "class" => "form-control", "id" => "fieldDate"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUserId" class="col-sm-2 control-label">User Of ID</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["User_ID", "type" => "number", "class" => "form-control", "id" => "fieldUserId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldReplay" class="col-sm-2 control-label">Replay</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["Replay", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldReplay"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
