<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["cp_forms_replies/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["cp_forms_replies/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
            <th>Forms Of Response</th>
            <th>Date</th>
            <th>User Of ID</th>
            <th>Replay</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $cp_forms_replie): ?>
            <tr>
                <td><?php echo $cp_forms_replie->ID ?></td>
            <td><?php echo $cp_forms_replie->Forms_Response ?></td>
            <td><?php echo $cp_forms_replie->Date ?></td>
            <td><?php echo $cp_forms_replie->User_ID ?></td>
            <td><?php echo $cp_forms_replie->Replay ?></td>

                <td><?php echo $this->tag->linkTo(["cp_forms_replies/edit/" . $cp_forms_replie->ID, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["cp_forms_replies/delete/" . $cp_forms_replie->ID, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("cp_forms_replies/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("cp_forms_replies/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("cp_forms_replies/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("cp_forms_replies/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
